C:\Users\baihan\Google Drive\UbiComp_Doppler_Baihan\double_bone\double_bone-static_stress
C:\Users\baihan\Google Drive\UbiComp_Doppler_Baihan\double_bone\double_bone-Frequency 1
C:\Users\baihan\Google Drive\UbiComp_Doppler_Baihan\double_bone\double_bone-Frequency 1
C:\Users\baihan\Google Drive\UbiComp_Doppler_Baihan\double_bone\double_bone-static_stress
C:\Users\baihan\Google Drive\UbiComp_Doppler_Baihan\double_bone\double_bone-Frequency 2
C:\Users\baihan\Google Drive\UbiComp_Doppler_Baihan\double_bone\double_bone-Dynamic 1
